manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: bigwhale
      url-base: https://github.com/BigWhale
  projects:
    - name: zmk
      remote: bigwhale
      revision: fix/deep-sleep-wake-central
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
  self:
    path: config
